# Base image with CUDA, cuDNN, Python 3.10
FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Python 3.10 
RUN export DEBIAN_FRONTEND=noninteractive TZ=US && \
    apt-get update && \
    apt-get install -y \
        python3.10 \
        python3-pip \
        espeak \
        libespeak1 && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy files
COPY requirements.txt .
RUN apt-get update && apt-get install -y git
RUN pip install -r requirements.txt
COPY TTS_API.py .
COPY utils.py .
COPY models.py .
COPY StyleTTS2 /app/StyleTTS2

# Expose FastAPI default port
EXPOSE 8001

# Run the app using uvicorn
CMD ["uvicorn", "TTS_API:app", "--host", "0.0.0.0", "--port", "8001"]




