# Base image with CUDA, cuDNN, Python 3.10
FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Python 3.10 
RUN export DEBIAN_FRONTEND=noninteractive TZ=US && \
    apt-get update && \
    apt-get -y install python3.10 python3-pip

# Set working directory
WORKDIR /app

# Copy files
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY API_LLAMA3_2.py .
COPY db.py .
COPY model.py .
COPY utils.py .
COPY prompt.py .


# Expose FastAPI default port
EXPOSE 4096

# Run the app using uvicorn
CMD ["uvicorn", "API_LLAMA3_2:app", "--host", "0.0.0.0", "--port", "4096"]




